/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import COMMAND.commandexcut;
import COMMAND.seatshiftcommand.Command;
import FILE.Seat2DB;
import SEAT.Seatinfo;
import SEAT.seatshiftdata;
import SEAT.seatshiftdata2;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Free
 */
public class seatshif2 extends javax.swing.JFrame {

    ArrayList<Seatinfo> Seat = new ArrayList<>();
    Seat2DB user = new Seat2DB();
    login lg = new login();
    String e = lg.a;
    /**
     * Creates new form Seat
     */
    int aprice = 10000;
    int bprice = 20000;
    int cprice = 30000;
    String seat1 = "a1";
    String seat2 = "a2";
    String seat3 = "a3";
    String seat4 = "a4";
    String seat5 = "b1";
    String seat6 = "b2";
    String seat7 = "b3";
    String seat8 = "b4";
    String seat9 = "c1";
    String seat10 = "c2";
    String seat11 = "c3";
    String seat12 = "c4";

    public seatshif2() {
        initComponents();

        user.DB();
        user.Split();

        try {
            Seat = user.returnSeatDB();
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int a = 0; a < Seat.size(); a++) {
            if (Seat.get(a).getseat().equals(seat1)) {
                a1.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat2)) {
                a2.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat3)) {
                a3.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat4)) {
                a4.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat5)) {
                b1.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat6)) {
                b2.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat7)) {
                b3.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat8)) {
                b4.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat9)) {
                c1.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat10)) {
                c2.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat11)) {
                c3.setEnabled(false);
            }
            if (Seat.get(a).getseat().equals(seat12)) {
                c4.setEnabled(false);
            }
        }
    }

    public void data(String e) {
        seatshiftdata data2 = new seatshiftdata();
        Command seatshiftdata2 = new seatshiftdata2(data2);

        commandexcut excut = new commandexcut(seatshiftdata2);
        excut.pressed();

        seatshift st = new seatshift();
        st.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a1.setText("a1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        a2.setText("a2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        b1.setText("b1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("b2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        c2.setText("c2");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        a4.setText("a4");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        c1.setText("c1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        a3.setText("a3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        b3.setText("b3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("b4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        c3.setText("c3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c4.setText("c4");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        jLabel1.setText(" 통로");
        jLabel1.setMaximumSize(new java.awt.Dimension(24, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(24, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(24, 15));

        jLabel2.setText("A-200");

        jLabel3.setText("10000");

        jLabel4.setText("20000");

        jLabel5.setText("30000");

        jButton1.setText("취소");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(b3)
                                            .addComponent(a3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(a4)
                                            .addComponent(b4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(c3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c4)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(c1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c2)))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a3)
                                .addComponent(a4))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b4)
                                .addComponent(b3))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(c3)
                                .addComponent(c4)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a1)
                                .addComponent(a2)
                                .addComponent(jLabel3))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b1)
                                .addComponent(b2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(c2)
                                .addComponent(c1))))
                    .addComponent(jLabel5))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat1 + " " + e + " " + aprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                a1.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                a1.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat2 + " " + e + " " + aprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                a2.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                a2.setEnabled(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_a2ActionPerformed
    }
    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat3 + " " + e + " " + aprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                a3.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                a3.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat4 + " " + e + " " + aprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                a4.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                a4.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_a4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat5 + " " + e + " " + bprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                b1.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                b1.setEnabled(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat6 + " " + e + " " + bprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                b2.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                b2.setEnabled(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat7 + " " + e + " " + bprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                b3.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                b3.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat8 + " " + e + " " + bprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                b4.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                b4.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat9 + " " + e + " " + cprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                c1.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                c1.setEnabled(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat10 + " " + e + " " + cprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                c2.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                c2.setEnabled(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat11 + " " + e + " " + cprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                c3.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                c3.setEnabled(true);
            }

        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:

        try {
            int choose = JOptionPane.showConfirmDialog(null, "좌석을 수정하시겠습니까?", "수정 확인창", JOptionPane.YES_NO_OPTION);
            data(e);
            if (choose == JOptionPane.YES_OPTION) {
                user.DBWrite(seat12 + " " + e + " " + cprice);
                user.Split();
                JOptionPane.showMessageDialog(null, "좌석이 수정되었습니다.");
                c4.setEnabled(false);
            } else if (choose == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "좌석이 수정되지 않았습니다. 다시 선택해주세요.");
                c4.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(Seat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_c4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        seatshift ssh = new seatshift();
        ssh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seat2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
