/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hun24
 */
public class Check extends javax.swing.JFrame {

    /**
     * Creates new form Check
     */
    File booking = new File("C:\\DB\\Book.txt");
    File scheck1 = new File("C:\\DB\\Seat.txt");
    File scheck2 = new File("C:\\DB\\Seat2.txt");
    File scheck3 = new File("C:\\DB\\Seat3.txt");
    int s = 0;

    public Check() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id_Text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search_BT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("항공권 확인");

        jLabel2.setText("ID");

        Search_BT.setText("검색");
        Search_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BTActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "비행기", "출발지", "도착지", "출발 시간", "도착 시간", "좌석"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("확인");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("항공권 취소");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("이전");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Id_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search_BT))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Id_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_BT))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BTActionPerformed

        String name = Id_Text.getText();

        int numa = 0;
        int numb = 0;
        int numc = 0;

        String temps = "";
        String temps1 = "";
        String temps2 = "";
        String temps3 = "";

        String a = "";
        String b = "";
        String c = "";

        String[] resulta;
        String[] resulta1;
        String[] resulta2;
        String[] resulta3;

        DefaultTableModel search;
        search = (DefaultTableModel) jTable1.getModel();

        try {
            BufferedReader txtread = new BufferedReader(new FileReader(new File("C:\\DB\\Book.txt")));

            BufferedReader txtread1 = new BufferedReader(new FileReader(new File("C:\\DB\\seat.txt")));

            BufferedReader txtread2 = new BufferedReader(new FileReader(new File("C:\\DB\\seat2.txt")));

            BufferedReader txtread3 = new BufferedReader(new FileReader(new File("C:\\DB\\seat3.txt")));

            if (name.length() == 0) {
                JOptionPane.showMessageDialog(null, "ID를 확인하세요");
            } else {
                while ((temps1 = txtread1.readLine()) != null) {
                    resulta1 = temps1.split(" ");
                    if (name.equals(resulta1[1])) {
                        numa = 1;
                        a = resulta1[0];
                    }
                }

                while ((temps2 = txtread2.readLine()) != null) {
                    resulta2 = temps2.split(" ");
                    if (name.equals(resulta2[1])) {
                        numb = 1;
                        b = resulta2[0];
                    }
                }

                while ((temps3 = txtread3.readLine()) != null) {
                    resulta3 = temps3.split(" ");
                    if (name.equals(resulta3[1])) {
                        numc = 1;
                        c = resulta3[0];
                    }
                }

                if (numa == 1) {
                    while ((temps = txtread.readLine()) != null) {
                        resulta = temps.split(" ");
                        if (name.equals(resulta[0])) {
                            search.insertRow(search.getRowCount(), new Object[]{
                                resulta[0],
                                resulta[1],
                                resulta[2],
                                resulta[3],
                                resulta[4] + "-" + resulta[5] + "-" + resulta[6],
                                resulta[4] + "-" + resulta[7] + "-" + resulta[8],
                                a
                            });
                        }
                    }
                }

                if (numb == 1) {
                    while ((temps = txtread.readLine()) != null) {
                        resulta = temps.split(" ");
                        if (name.equals(resulta[0])) {
                            search.insertRow(search.getRowCount(), new Object[]{
                                resulta[0],
                                resulta[1],
                                resulta[2],
                                resulta[3],
                                resulta[4] + "-" + resulta[5] + "-" + resulta[6],
                                resulta[4] + "-" + resulta[7] + "-" + resulta[8],
                                b
                            });
                        }
                    }
                }

                if (numc == 1) {
                    while ((temps = txtread.readLine()) != null) {
                        resulta = temps.split(" ");
                        if (name.equals(resulta[0])) {
                            if (numc == 1) {
                                search.insertRow(search.getRowCount(), new Object[]{
                                    resulta[0],
                                    resulta[1],
                                    resulta[2],
                                    resulta[3],
                                    resulta[4] + "-" + resulta[5] + "-" + resulta[6],
                                    resulta[4] + "-" + resulta[7] + "-" + resulta[8],
                                    c
                                });
                            }
                        }
                    }
                }

                txtread.close();
                txtread1.close();
                txtread2.close();
                txtread3.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChangeLine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChangeLine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Search_BTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usermain us = new usermain();
        us.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        String a = (String) jTable1.getValueAt(row, 0);

        String[] cancel;
        String[] rm1;
        String[] rm2;
        String[] rm3;

        String addcancel = "";
        String dseat1 = "";
        String dseat2 = "";
        String dseat3 = "";

        String line;
        String dline1;
        String dline2;
        String dline3;

        FileInputStream add;
        FileInputStream delete1;
        FileInputStream delete2;
        FileInputStream delete3;

        try {
            add = new FileInputStream(booking);
            InputStreamReader isr = new InputStreamReader(add);
            BufferedReader cadd = new BufferedReader(isr);

            delete1 = new FileInputStream(scheck1);
            InputStreamReader isr1 = new InputStreamReader(delete1);
            BufferedReader cadd1 = new BufferedReader(isr1);

            delete2 = new FileInputStream(scheck2);
            InputStreamReader isr2 = new InputStreamReader(delete2);
            BufferedReader cadd2 = new BufferedReader(isr2);

            delete3 = new FileInputStream(scheck3);
            InputStreamReader isr3 = new InputStreamReader(delete3);
            BufferedReader cadd3 = new BufferedReader(isr3);

            while ((line = cadd.readLine()) != null) {
                cancel = line.split(" ");

                if (!a.equals(cancel[0])) {
                    addcancel += (line + "\r\n");
                    s = 1;
                }
            }
            if (s == 1) {
                JOptionPane.showMessageDialog(null, "취소되었습니다.");
            }

            while ((dline1 = cadd1.readLine()) != null) {
                rm1 = dline1.split(" ");

                if (!a.equals(rm1[1])) {
                    dseat1 += (dline1 + "\r\n");
                    s = 1;
                }
            }
            while ((dline2 = cadd2.readLine()) != null) {
                rm2 = dline2.split(" ");

                if (!a.equals(rm2[1])) {
                    dseat2 += (dline2 + "\r\n");
                    s = 1;
                }
            }
            while ((dline3 = cadd3.readLine()) != null) {
                rm3 = dline3.split(" ");

                if (!a.equals(rm3[1])) {
                    dseat3 += (dline3 + "\r\n");
                    s = 1;

                }
            }
            FileWriter addfw = new FileWriter(booking);
            addfw.write(addcancel);
            addfw.close();

            FileWriter deletefw1 = new FileWriter(scheck1);
            deletefw1.write(dseat1);
            deletefw1.close();

            FileWriter deletefw2 = new FileWriter(scheck2);
            deletefw2.write(dseat2);
            deletefw2.close();

            FileWriter deletefw3 = new FileWriter(scheck3);
            deletefw3.write(dseat3);
            deletefw3.close();

            cadd.close();
            cadd1.close();
            cadd2.close();
            cadd3.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(admain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(admain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        usermain a = new usermain();
        a.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_Text;
    private javax.swing.JButton Search_BT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
