/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import FILE.A;
import FILE.UserID;
import USER.LogInfo;
import USER.LogInfoBuilder;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class User extends javax.swing.JFrame {

    ArrayList<LogInfo> User = new ArrayList<>();

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(men);
        bg.add(women);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        men = new javax.swing.JRadioButton();
        women = new javax.swing.JRadioButton();
        check_user = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        check_id = new javax.swing.JButton();
        pw = new javax.swing.JTextField();
        check_pw = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("회원가입");

        jLabel2.setText("Name:");

        jLabel3.setText("ID:");

        jLabel4.setText("PW:");

        jLabel5.setText("Check PW:");

        jLabel6.setText("Phone:");

        jLabel7.setText("gender:");

        men.setText("men");

        women.setText("women");
        women.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                womenActionPerformed(evt);
            }
        });

        check_user.setText("가입");
        check_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_userActionPerformed(evt);
            }
        });

        name.setToolTipText("");

        id.setToolTipText("");

        check_id.setText("중복");
        check_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_idActionPerformed(evt);
            }
        });

        pw.setToolTipText("");

        check_pw.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(men)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(women))
                    .addComponent(name)
                    .addComponent(id)
                    .addComponent(pw)
                    .addComponent(check_pw)
                    .addComponent(phone))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(check_user)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(check_id)
                        .addGap(177, 177, 177))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(check_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(men)
                    .addComponent(women))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_user)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void womenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_womenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_womenActionPerformed

    private void check_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_idActionPerformed
        //UserID user = new UserID();
        A sr = new A();
        sr.DB();
        sr.Split();
        try {
            User = sr.returnLogInfo();
        } catch (IOException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        String ID = id.getText();
        int count = 1;
        if(id.getText().length() == 0 || name.getText().length() == 0){
             JOptionPane.showMessageDialog(null, ("이름 혹은 아이디를 입력하지 않았습니다."));
        }else{
        for (int a = 0; a < User.size(); a++) {
            if (User.get(a).getId().equals(ID)) {
                JOptionPane.showMessageDialog(null, ("중복되는 아이디입니다.."));
                id.setText("");
                count = 0;
                break;
            }
        }
        if (count == 1) {
            JOptionPane.showMessageDialog(null, ("사용가능한 아이디입니다."));
        }
        }
    }//GEN-LAST:event_check_idActionPerformed

    private void check_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_userActionPerformed
        UserID user = new UserID();
        
        String ID = id.getText();
        String PW = pw.getText();

       
        LogInfoBuilder logInfoBuilder = new LogInfoBuilder();
        LogInfo result = logInfoBuilder.setId(ID + " ")
                .setPw(PW + " ")
                .build();
        
         String PHONE = phone.getText();
        String NAME = name.getText();
                String GENDER = "남";
        if (men.isSelected() == true) {
            GENDER = "남";
        } else if (women.isSelected() == true) {
            GENDER = "여 ";
        }
        String a = result.getPersonInfo() + " " + NAME + " "+ PHONE + " " + GENDER ;

        if (name.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, ("이름이 입력되지 않았습니다."));
        } else if (id.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, ("아이디가 입력되지 않았습니다."));
        } else if (pw.getText().length() == 0 || check_pw.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, ("비밀번호 또는 비밀번호 확인이 입력되지 않았습니다 "));
        } else if (check_pw.getText().equals(pw.getText()) == false) {
            JOptionPane.showMessageDialog(null, ("비밀번호 또는 비밀번호 확인의 입력이 다릅니다."));
        } else if (men.isSelected() == false && women.isSelected() == false) {
            JOptionPane.showMessageDialog(null, ("성별이 선택되지 않았습니다."));
        } else {
            try {
                user.DBWrite(a);
                user.Split();

                JOptionPane.showMessageDialog(null, ("회원가입이 완료되었습니다."));
                login next = new login();
                next.setVisible(true);
                dispose();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ("회원가입이 실패했습니다"));
            }
            dispose();
        }
    }//GEN-LAST:event_check_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_id;
    private javax.swing.JTextField check_pw;
    private javax.swing.JButton check_user;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton men;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pw;
    private javax.swing.JRadioButton women;
    // End of variables declaration//GEN-END:variables
}
